### ISSUE TITLE
tools.lua:7 Lua Error: bad argument #1 to 'rshift' (number expected, got nil)

### ISSUE THREAD

**Issue by ChillerDragon** [nheir/tw-dissect#4]
![twdissect_nil_shift_err](https://user-images.githubusercontent.com/20344300/89879128-c5639e80-dbc2-11ea-8532-ee0663929f78.png)

Seems to be only reproducible using [ZillyWoods](https://zillywoods.github.io/ZillyWoods-web/) client

**Comment by nheir** [comment]
running manually the analysis from cli works fine on this short hex dump

```000a -> flag 0, ack 0a
02 -> #chunks 02
5e525ecb -> token
  401205 -> flag 1, size 18, sequence 5
    00 -> type 0, system 0
    effeaf552c473ea0952d773f726168ee01 -> data
  0012 -> flag 0, size 18
  	29 -> type 20, system 1 (input)
  		9625 -> ackTick 2390 
  		9725 -> predTick 2391
  		28 -> Size 40
  		00 cd04 e504 00 04 00 00 00 00 00
```

According to the screen, unpack_int fails on ackTick, predTick or Size.

can you provide a full dump so I can run wireshark on for further research ?

**Comment by ChillerDragon** [comment]
@nheir o.O how to run it from cli?

I stopped using ZillyWoods and 0.7 and downgraded to ddnet 0.6 latley so I have to admit I am not too interested in this currently and too lazy to censor a dump so I do not leak any personal data.

But it should be very easy to reproduce by using ZillyWoods client.

**Comment by nheir** [comment]
> @nheir o.O how to run it from cli?

with some difficulties, using lua directly and copy/paste part of the parser that do not rely on wireshark interface
I wanted to separate wireshark stuff from packet structure decoding but there is still many places that mix both...

> I stopped using ZillyWoods and 0.7 and downgraded to ddnet 0.6 latley so I have to admit I am not too interested in this currently and too lazy to censor a dump so I do not leak any personal data.
>
> But it should be very easy to reproduce by using ZillyWoods client.

I won't try

**Comment by ChillerDragon** [comment]
> with some difficulties, using lua directly and copy/paste part of the parser that do not rely on wireshark interface
> I wanted to separate wireshark stuff from packet structure decoding but there is still many places that mix both...

Oh sad I thought there is a nice cli wireshark version :/

> I won't try

Guess if nobody has interested closing this issue for now

**Comment by nheir** [comment]
in fact, I ve just find that ZillyWoods don't send a field that the server now is expecting:
https://github.com/ZillyWoods/ZillyWoods/blob/5b9d9a5d000da0fd4a80d05fd4172081ec842fee/src/engine/client/client.cpp#L420

vs

https://github.com/teeworlds/teeworlds/blob/e7fe3333271604e1d4cda0a7124c7ca841451124/src/engine/client/client.cpp#L425

introduced here https://github.com/teeworlds/teeworlds/commit/77924b4254b79551d173a261080447dd99b2ebcd

**Comment by ChillerDragon** [comment]
oh
